### ISSUE TITLE
scalajs 1.0.0-M1 build

### ISSUE THREAD

**Issue by chandu0101** [outr/reactify#15]
I want to try reactify in one of my project (which is on 1.0.0-M1) , can you publish for scalajs 1.0.0-M1 after this issue : https://github.com/scalatest/scalatest/issues/1178 closed....

**Comment by darkfrog26** [comment]
@chandu0101 sure, just remind me once that ticket is closed and I'll do a build for it.

**Comment by darkfrog26** [comment]
I've added integration for using Scala.js 1.0.0-M1, but cannot release it until that bug is resolved in ScalaTest.

**Comment by darkfrog26** [comment]
@chandu0101 I did a special release of Reactify 2.2.0 for Scala.js 1.0.0-M1.  Hopefully, that will allow you to start using it in your project.  Let me know if you have any problems.  Once ScalaTest is working properly with it I'll start cross-building.

**Comment by chandu0101** [comment]
@darkfrog26  thank  you :)
